"use client";

import { useEffect, useMemo, useState } from "react";

type View = "overview" | "customers" | "sellers" | "orders" | "revenue" | "traffic" | "catalogue" | "support" | "activity" | "reports" | "settings";
type Seller = { storeName: string; type: string; city: string; approved: boolean; products: number; liveProducts: number; stock: number; lowStock: number; orderValue: number; orders: number; updatedAt: string };
type Order = { id: string; date: string; status: string; total: number; fulfilment: string; itemCount: number; city: string; sellerNames: string[] };
type Feed = {
  generatedAt: string; privacy: { message: string; excludes: string[] }; metrics: Record<string, number>;
  analytics: { daily: Array<{ date: string; visits: number; signups: number; orders: number; productViews: number; cartAdds: number; errors: number }>; sources: Array<{ source: string; events: number }>; funnel: Array<{ label: string; value: number }> };
  customerSegments: { registeredCustomers: number; purchasingCustomers: number; repeatPurchasers: number; abandonedCarts: number; wishlistOnly: number };
  revenueSummary: { recordedOrderValue: number; cancelledOrderValue: number; averageOrderValue: number; paymentProviderConnected: boolean; platformRevenueAvailable: boolean };
  fulfilment: { delivery: number; collection: number }; alerts: { pendingSellers: number; lowStockProducts: number; ordersToPrepare: number };
  sellers: Seller[]; orders: Order[]; activity: Array<{ id: string; event: string; actorKind: string; createdAt: string }>;
};
const EMPTY: Feed = { generatedAt: "", privacy: { message: "Private information is intentionally excluded.", excludes: [] }, metrics: {}, analytics: { daily: [], sources: [], funnel: [] }, customerSegments: { registeredCustomers: 0, purchasingCustomers: 0, repeatPurchasers: 0, abandonedCarts: 0, wishlistOnly: 0 }, revenueSummary: { recordedOrderValue: 0, cancelledOrderValue: 0, averageOrderValue: 0, paymentProviderConnected: false, platformRevenueAvailable: false }, fulfilment: { delivery: 0, collection: 0 }, alerts: { pendingSellers: 0, lowStockProducts: 0, ordersToPrepare: 0 }, sellers: [], orders: [], activity: [] };
const nav: Array<[View, string]> = [["overview","Overview"],["customers","Customers"],["sellers","Sellers"],["orders","Orders"],["revenue","Revenue"],["traffic","Traffic & Discovery"],["catalogue","Catalogue"],["support","Reviews & Support"],["activity","Activity"],["reports","Reports"],["settings","Settings"]];
const money = (value = 0) => `N$${Math.round(value).toLocaleString("en-NA")}`;
const pct = (part = 0, total = 0) => total ? `${Math.round(part / total * 100)}%` : "0%";
const relative = (value: string) => { const m = Math.max(0, Math.round((Date.now() - new Date(value).getTime()) / 60000)); return m < 60 ? `${m}m ago` : m < 1440 ? `${Math.floor(m / 60)}h ago` : `${Math.floor(m / 1440)}d ago`; };
function Metric({ label, value, note, accent }: { label: string; value: string | number; note: string; accent?: boolean }) { return <article className={`metric-card ${accent ? "accent" : ""}`}><small>{label}</small><strong>{value}</strong><span>{note}</span></article>; }
function Empty({ title }: { title: string }) { return <div className="empty-state"><span>SM</span><h3>{title}</h3><p>Real activity will appear here when it is recorded.</p></div>; }

export default function AdminDashboard({ operatorName }: { operatorName: string }) {
  const [view, setView] = useState<View>("overview"); const [feed, setFeed] = useState<Feed>(EMPTY); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [range, setRange] = useState("30"); const [seller, setSeller] = useState("all");
  const refresh = async () => { setError(""); try { const r = await fetch("/api/dashboard", { cache: "no-store" }); const body = await r.json() as Feed & { error?: string }; if (!r.ok) throw new Error(body.error ?? "Unable to load business data"); setFeed(body); } catch (e) { setError(e instanceof Error ? e.message : "Unable to load business data"); } finally { setLoading(false); } };
  useEffect(() => { const first = window.setTimeout(() => void refresh(), 0); const timer = window.setInterval(() => void refresh(), 60000); return () => { clearTimeout(first); clearInterval(timer); }; }, []);
  const days = useMemo(() => feed.analytics.daily.slice(-Number(range)), [feed.analytics.daily, range]);
  const maxVisits = Math.max(1, ...days.map(d => d.visits)); const shownOrders = seller === "all" ? feed.orders : feed.orders.filter(o => o.sellerNames.includes(seller));
  const go = (next: View) => { setView(next); window.scrollTo({ top: 0, behavior: "smooth" }); };
  const download = () => { const rows = [["Order","Date","Status","Fulfilment","Town","Sellers","Recorded value"], ...shownOrders.map(o => [o.id,o.date,o.status,o.fulfilment,o.city,o.sellerNames.join(" | "),o.total])]; const csv = rows.map(row => row.map(value => `"${String(value).replaceAll('"','""')}"`).join(",")).join("\n"); const a = document.createElement("a"); a.href = URL.createObjectURL(new Blob([csv], { type: "text/csv" })); a.download = `stylishme-orders-${new Date().toISOString().slice(0,10)}.csv`; a.click(); URL.revokeObjectURL(a.href); };
  const intro: Record<View, string> = { overview: "Your marketplace today.", customers: "Understand customers without exposing them.", sellers: "Stores, stock and seller momentum.", orders: "Every recorded order in one place.", revenue: "Order value you can verify.", traffic: "How people discover StylishMe.", catalogue: "Marketplace catalogue health.", support: "Reviews and support.", activity: "Recent marketplace activity.", reports: "Export business records.", settings: "Private owner settings." };
  let content: React.ReactNode;
  if (view === "overview") content = <><section className="overview-hero"><div><small>STYLISHME OWNER OVERVIEW</small><h2>{feed.metrics.orders ? `${feed.metrics.orders} orders recorded.` : "Ready for the first real order."}</h2><p>A private, truthful view of customers, sellers, fulfilment and marketplace momentum.</p></div><div className="hero-number"><span>Recorded order value</span><strong>{money(feed.revenueSummary.recordedOrderValue)}</strong><small>Payment confirmation is not yet connected</small></div></section><section className="metrics-grid"><Metric label="CUSTOMERS" value={feed.customerSegments.registeredCustomers} note={`${feed.customerSegments.purchasingCustomers} have ordered`} /><Metric label="ACTIVE SELLERS" value={feed.metrics.approvedSellers ?? 0} note={`${feed.metrics.sellers ?? 0} seller records`} /><Metric label="ORDERS" value={feed.metrics.orders ?? 0} note={`${feed.metrics.activeOrders ?? 0} in progress`} accent /><Metric label="CONVERSION" value={`${feed.metrics.checkoutConversion ?? 0}%`} note="Checkout starts to orders" /></section><section className="overview-grid"><article className="panel activity-chart"><div className="panel-title"><div><small>ACTIVITY WINDOW</small><h3>Visits</h3></div><span>Anonymous events only</span></div><div className="bars">{days.map(d => <div key={d.date}><span style={{height:`${Math.max(5,d.visits/maxVisits*100)}%`}}><b>{d.visits || ""}</b></span><small>{new Date(d.date).toLocaleDateString("en-NA",{weekday:"short"})}</small></div>)}</div></article><article className="panel attention-panel"><div className="panel-title"><div><small>NEEDS ATTENTION</small><h3>Marketplace health</h3></div></div><button onClick={() => go("orders")}><i className="coral"/><div><strong>Orders to prepare</strong><small>Delivery and collection need different handling</small></div><b>{feed.alerts.ordersToPrepare}</b></button><button onClick={() => go("sellers")}><i className="lilac"/><div><strong>Low-stock products</strong><small>Across all seller catalogues</small></div><b>{feed.alerts.lowStockProducts}</b></button><button onClick={() => go("customers")}><i className="sand"/><div><strong>Carts in progress</strong><small>Anonymous aggregate only</small></div><b>{feed.customerSegments.abandonedCarts}</b></button></article></section></>;
  else if (view === "customers") content = <><section className="metrics-grid"><Metric label="REGISTERED" value={feed.customerSegments.registeredCustomers} note="Customer accounts" accent/><Metric label="PURCHASERS" value={feed.customerSegments.purchasingCustomers} note={pct(feed.customerSegments.purchasingCustomers,feed.customerSegments.registeredCustomers)} /><Metric label="REPEAT" value={feed.customerSegments.repeatPurchasers} note="More than one order"/><Metric label="SAVED ONLY" value={feed.customerSegments.wishlistOnly} note="Saved pieces, no order"/></section><section className="privacy-hero"><small>PRIVATE BY DESIGN</small><h2>Patterns, not private profiles.</h2><p>{feed.privacy.message} Customer-level names and contact details are deliberately unavailable in analytics.</p></section></>;
  else if (view === "sellers") content = <section className="seller-grid">{feed.sellers.map((s,i)=><article key={s.storeName}><div className={`seller-monogram tone-${i%3+1}`}>{s.storeName.slice(0,2).toUpperCase()}</div><div className="seller-copy"><small>{s.type} · {s.city}</small><h3>{s.storeName}</h3><p>{s.liveProducts} live of {s.products} products</p><span className={s.approved?"approved":"pending"}>{s.approved?"Quality checks passed":"Not live"}</span></div><dl><div><dt>ORDERS</dt><dd>{s.orders}</dd></div><div><dt>VALUE*</dt><dd>{money(s.orderValue)}</dd></div><div><dt>STOCK</dt><dd>{s.stock}</dd></div></dl><footer><small>Catalogue-attributed value</small><span>{s.lowStock} low stock</span></footer></article>)}{!feed.sellers.length&&<Empty title="No sellers yet"/>}</section>;
  else if (view === "orders") content = <section className="panel table-panel"><div className="table-head"><span>Order</span><span>Seller</span><span>Fulfilment</span><span>Items</span><span>Value</span></div>{shownOrders.map(o=><article className="order-row" key={o.id}><div><strong>{o.id}</strong><small>{o.date || "Date unavailable"}</small></div><div><strong>{o.sellerNames.join(", ") || "Seller unavailable"}</strong><small>{o.city}</small></div><div><strong>{o.fulfilment}</strong><small>{o.status}</small></div><span>{o.itemCount}</span><b>{money(o.total)}</b></article>)}{!shownOrders.length&&<Empty title="No recorded orders"/>}</section>;
  else if (view === "revenue") content = <><section className="metrics-grid"><Metric label="RECORDED ORDER VALUE" value={money(feed.revenueSummary.recordedOrderValue)} note="Cancelled orders excluded" accent/><Metric label="AVERAGE ORDER" value={money(feed.revenueSummary.averageOrderValue)} note="Recorded order value"/><Metric label="CANCELLED VALUE" value={money(feed.revenueSummary.cancelledOrderValue)} note="Not included in total"/><Metric label="PLATFORM REVENUE" value="Unavailable" note="Commission accounting not connected"/></section><section className="privacy-hero"><small>FINANCIAL TRUTH</small><h2>Orders are recorded; paid sales are not yet verified.</h2><p>A verified payment provider, settlement records and commission rules must be connected before this panel can report paid sales, fees, refunds or payouts.</p></section></>;
  else if (view === "traffic") content = <><section className="panel stock-panel">{feed.analytics.sources.map(s=><article key={s.source}><div><strong>{s.source}</strong><small>Privacy-safe source label</small></div><div className="health-bar"><i style={{width:`${s.events/Math.max(1,feed.analytics.sources[0]?.events??1)*100}%`}}/></div><span>{s.events}</span></article>)}{!feed.analytics.sources.length&&<Empty title="No discovery data yet"/>}</section><section className="panel stock-panel">{feed.analytics.funnel.map((f,i)=><article key={f.label}><div><strong>{f.label}</strong><small>{f.value} recorded</small></div><div className="health-bar"><i style={{width:`${f.value/Math.max(1,feed.analytics.funnel[0]?.value??1)*100}%`}}/></div><span>{i?pct(f.value,feed.analytics.funnel[i-1].value):"100%"}</span></article>)}</section></>;
  else if (view === "catalogue") content = <><section className="metrics-grid"><Metric label="PRODUCTS" value={feed.metrics.products??0} note="Across seller records"/><Metric label="LOW STOCK" value={feed.alerts.lowStockProducts} note="Needs seller attention" accent/><Metric label="SELLERS" value={feed.metrics.sellers??0} note={`${feed.metrics.approvedSellers??0} active`}/><Metric label="QUALITY RULE" value="Automatic" note="Completeness, stock, images and safety"/></section><section className="privacy-hero"><small>PUBLISHING STANDARD</small><h2>Listings publish only after deterministic checks pass.</h2><p>No routine manual approval queue. Incomplete, unsafe or out-of-stock submissions remain unavailable until corrected.</p></section></>;
  else if (view === "activity") content = <section className="panel activity-log">{feed.activity.slice(0,80).map(a=><article key={a.id}><time>{relative(a.createdAt)}</time><i/><div><strong>{a.event.replaceAll("_"," ")}</strong><small>{a.actorKind}</small></div></article>)}{!feed.activity.length&&<Empty title="No activity yet"/>}</section>;
  else if (view === "reports") content = <section className="privacy-hero"><small>BUSINESS EXPORTS</small><h2>Download the records behind this view.</h2><p>The order export follows the current seller filter and excludes customer names, contact details, addresses and payment details.</p><button className="report-button" onClick={download}>Download report</button></section>;
  else content = <section className="privacy-hero"><small>PLANNED AREA</small><h2>{view === "support" ? "Support reporting needs a real support source." : "Owner controls will grow with the marketplace."}</h2><p>{view === "support" ? "Reviews and support metrics are not collected yet, so this page intentionally shows no invented tickets or ratings." : "Access remains restricted to the StylishMe owner. More settings will be added only when they control a real service."}</p></section>;
  return <main className="admin-stage"><aside className="side-nav"><button className="admin-brand" onClick={()=>go("overview")}><strong>STYLISHME</strong><small>OWNER</small></button><nav>{nav.map(([target,label])=><button key={target} className={view===target?"active":""} onClick={()=>go(target)}><i>·</i><span>{label}</span></button>)}</nav><div className="operator"><span>{operatorName.slice(0,1).toUpperCase()}</span><div><strong>{operatorName}</strong><small>Private owner access</small></div></div></aside><section className="admin-main"><header className="topbar"><div><small>{view.toUpperCase()}</small><h1>{intro[view]}</h1></div><div className="top-actions"><select aria-label="Activity range" value={range} onChange={e=>setRange(e.target.value)}><option value="7">7 days</option><option value="30">30 days</option></select><select aria-label="Seller filter" value={seller} onChange={e=>setSeller(e.target.value)}><option value="all">All sellers</option>{feed.sellers.map(s=><option key={s.storeName}>{s.storeName}</option>)}</select><button onClick={()=>void refresh()} disabled={loading}>{loading?"Refreshing...":"Refresh"}</button><button onClick={download}>Download report</button><a href="/signout-with-chatgpt?return_to=/">Sign out</a></div></header>{error&&<div className="error-banner"><strong>Business data paused</strong><span>{error}</span><button onClick={()=>void refresh()}>Try again</button></div>}<div className="content">{content}</div><footer className="admin-footer"><span>Private StylishMe business control centre</span><small>{feed.generatedAt?`Updated ${relative(feed.generatedAt)}`:"Waiting for real data"}</small></footer></section><nav className="mobile-nav">{nav.slice(0,5).map(([target,label])=><button key={target} onClick={()=>go(target)} className={view===target?"active":""}><i>·</i><span>{label}</span></button>)}</nav></main>;
}
